### ISSUE TITLE
'dict' error

### ISSUE THREAD

**Issue by inspectorpacket-OG** [goranjovic55/Binance-Trading-Bot#10]
Using USDT as pair

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pbp/goranjovic55/Binance-Trading-Bot/pausebotmod.py", line 59, in do_work
    paused = analyze()
  File "/home/pbp/goranjovic55/Binance-Trading-Bot/pausebotmod.py", line 44, in analyze
    ma_analysis = analysis.moving_averages[TYPE]
AttributeError: 'dict' object has no attribute 'moving_averages'

**Comment by Row-Bear** [comment]
Figured out the cause, not yet solution.
pausebotmod.py has 
SYMBOL = parsed_config['trading_options']['PAIR_WITH'] + 'USDT'
if we pair with USDT that won't work. Not sure what symbol pausebot should check then, but BTCUSDT at least gets rid of the error
