### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'moving_averages'

### ISSUE THREAD

**Issue by thesewerchild** [goranjovic55/Binance-Trading-Bot#81]
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/joey/Desktop/BinanceBot/modules/pausebotmod.py", line 69, in do_work
    paused = analyze()
  File "/home/joey/Desktop/BinanceBot/modules/pausebotmod.py", line 53, in analyze
    ma_analysis = analysis.moving_averages[TYPE]
AttributeError: 'dict' object has no attribute 'moving_averages'

**Comment by Chris-home17** [comment]
Same error for me every time I start the script

```
[2021-08-08 14:46:19] Press Ctrl-Q to stop the script
[2021-08-08 14:46:19] Starting modules.pausebotmod
[2021-08-08 14:46:20] pausebotmod:
[2021-08-08 14:46:20] Exception:
[2021-08-08 14:46:20] Exchange or symbol not found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/chrisdw/Documents/Developer/Binance-Trading-Bot-Binance-Trading-Bot 3/modules/pausebotmod.py", line 69, in do_work
    paused = analyze()
  File "/Users/chrisdw/Documents/Developer/Binance-Trading-Bot-Binance-Trading-Bot 3/modules/pausebotmod.py", line 53, in analyze
    ma_analysis = analysis.moving_averages[TYPE]
AttributeError: 'dict' object has no attribute 'moving_averages'
[2021-08-08 14:46:21] Starting modules.signalsamplemod
[2021-08-08 14:46:21] No module named 'modules.signalsamplemod'

```
